### ISSUE TITLE
Out-off-proportion CPU load

### ISSUE THREAD

**Issue by NavierStokesPDE** [capajon/r6maps#25]
Constantly about 30% CPU load (2x1.9GHz, 4 threads) when regarding any map in 2x2 view (still 20-25% in single view), peaks to 50% when moving the mouse over the map selection screen (each zooms and unzooms), drops back to idle when another tab is selected. This is on Win 7 64-bit on Firefox 49.
IE seems to be limited to one thread, caps at 25% with stuttering when trying to pan.

This might not be that noteable on gaming desktops.

X-posted this here from reddit

**Comment by capajon** [comment]
I'm okay with a bit of a performance hit when panning or zooming with 4 maps, but not okay that it is constant CPU usage - gotta be hurting battery life...

I'm not seeing anything that drastic, even on midrange hardware, but I'll look into this more soon.

**Comment by szarroug3** [comment]
Same problem here on win 10 64-bit firefox 50.

**Comment by olliholliday** [comment]
It sits at a constant 35% CPU on firefox, between 8% and 10% constant on chrome for me. (win10).

definitely makes it unusable to have loaded on a second screen for me.

**Comment by capajon** [comment]
I'll start looking at this in more detail, I am seeing the issue in Firefox as well.  Chrome seems fine for me, but still higher than I think it should be.

**Comment by capajon** [comment]
Oh wow I'm stupid.  I'm really sorry I didn't look at this closer sooner. :( 

So the issue is the loading spinner I'm using - it is using css animations and it is sort of always on screen.  Wow.  So much battery power wasted, so many users inconvenienced because I wanted to be fancy and smart with CSS.  Sigh.

Okay, so I'll definitely have a fix in today, you should notice the site runs a TON better.  It will still have some janky performance when you're doing something intense like zooming with 4 panels up, but that shouldn't be nearly as concerning as this obviously.

Yar.  Thanks for raising this again.

**Comment by olliholliday** [comment]
fantastic thanks for taking a look

**Comment by olliholliday** [comment]
thanks again, it works perfectly now. just played a ton of games with it on my second screen and it's a literal game changer :D
